spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.107:3306/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.0.107
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.0.107
    port: 6379

server:
  port: 8081

PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

env:
  prod2222

girl:
  name: gexiao
  age: 11
